### ISSUE TITLE
Promise Error in Catalogue Service

### ISSUE THREAD

**Issue by marcofranke** [nimble-platform/frontend-service#2] opened 2017-06-27 09:26 UTC
After the commit, when the repository is cloned for testing purposes, there is the following error:

    src/app/catalogue/catalogue.service.ts(67,9): error TS2322: Type 'Promise<Response>' is not assignable to type 'Promise<Catalogue>'.
      Type 'Response' is not assignable to type 'Catalogue'.
       Property 'id' is missing in type 'Response'.

I am working on the following on Windows machine:

        node --version
        v8.0.0
        npm --version
        v5.0.0

Has this anything to do with the latest commit?

**Comment by oliver-jung** [comment] 2017-06-27 11:48
Not reproducable for LTS versions (node 6.10.0, npm 3.10.10).
Potential fix introduces with commit #391220db729c9a14fc74236b5472e151f8ca947c.

**Comment by oliver-jung** [comment] 2017-07-27 07:10
Due to major changes on the catalogue service and lack of reproducability / responses I am closing this issue.

**Closed by oliver-jung** 2017-07-27 07:10 UTC
Labels: question
