### ISSUE TITLE
Order List of Business Processes in Dashboard  by Date [19Jan2018-1226]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#23] opened 2018-02-07 11:28 UTC
Path:

https://nimble-platform.salzburgresearch.at/nimble/frontend/#/dashboard

Description of the issue:

The information requests are not sorted properly by time.

Cause of the issue:

Probably the sorting issue relates to the date/time format. Example: 12:23:50 AM is larger than 1:17:32 PM which is larger than 1:05:22 PM.

**Comment by oliver-jung** [comment] 2018-02-20 12:42
Could not reproduce. Entries in the dashboard should be sorted by dateTime using the 24h format

**Comment by jinnerbichler** [comment] 2018-02-28 10:14
Use moment.js in order to sort by actual date.

**Comment by oliver-jung** [comment] 2018-03-12 14:43
Resolved with commit d121841

**Closed by oliver-jung** 2018-03-12 14:43 UTC
Labels: affects user interface, enhancement, user experience
